config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#splash'
  get 'pages/splash', to: 'pages#splash'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# # Cocktails
# #   Create
#     # New
#     get 'cocktails/new', to: 'cocktails#new', as: 'new_cocktail'
#     # Create
#     post 'cocktails', to: 'cocktails#create'

#   # Read
#     # Index
#     get 'cocktails', to: 'cocktails#index'
#     # Show
#     get 'cocktails/:id', to: 'cocktails#show', as: 'cocktail'

#   # Update
#     # Edit
#     get 'cocktails/:id/edit', to: 'cocktails#edit', as: 'edit_cocktail'
#     # Update
#     patch 'cocktails/:id', to: 'cocktails#update'

#   # Destroy
#     delete 'cocktails/:id', to: 'cocktails#destroy', as: 'delete_cocktail'

# # Doses
#   # New
#     get 'cocktails/:cocktail_id/doses/new', to: 'doses#new'
#   # Create
#     post 'cocktails/:cocktail_id/doses', to: 'doses#create'

#   # Destroy
#     delete 'cocktails/:id/doses/:id', to: 'doses#destroy'

resources :cocktails do
  resources :doses, only: [:new, :create]
end
resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  belongs_to :user

  validates :name, presence: true, uniqueness: true
  mount_uploader :picture, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cocktails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def new
    @cocktail = Cocktail.new
    authorize @cocktail
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.user = current_user
    authorize @cocktail
    if @cocktail.valid?
      @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def index
    @cocktails = Cocktail.all
    @cocktails = policy_scope(Cocktail)
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    authorize @cocktail
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
    authorize @cocktail
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    authorize @cocktail
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    cocktail = Cocktail.find(params[:id])
    cocktail.destroy
    redirect_to cocktails_path
  end
end

private

def cocktail_params
  params.require(:cocktail).permit(:name, :picture)
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    authorize @dose
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    authorize @dose
    if @dose.valid?
      @dose.save
      redirect_to cocktail_path(@dose[:cocktail_id])
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose[:cocktail_id])
  end
end

private

def dose_params
  params.require(:dose).permit(:description, :ingredient_id)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :splash

  def splash
    @hide = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name, label: 'Name:', placeholder: "Sex on the beach" %>
  <div class="picture_button">
  <%= f.input :picture %>
  </div>
  <%= f.input :picture_cache, as: :hidden %>
  <%= f.submit 'Add cocktail' %>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Edit cocktail:</h1>
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/index.html.erb
<h1>Pick your poison</h1>

<div class="container">
  <div class="row">
<% @cocktails.each do |c| %>
<%= link_to cocktail_path(c) do %>
<div class="col-xs-12 col-sm-4">
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path c.picture %>');">
  <div class="card-description">
    <h2><%= c.name %></h2>
  </div>
</div>
</div>
<% end %>
<% end %>
</div>
</div>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail:</h1>
<div class="form">
<%= render 'form', cocktail: @cocktail %>
</div>

app/views/cocktails/show.html.erb
<h1 class="cocktail"><%= @cocktail.name.titleize %></h1>
<%= cl_image_tag @cocktail.picture, id: 'cocktail_image' %>
<ul class="show">
<h4>Ingredients:</h4>
<% @cocktail.doses.each do |d| %>
<li><%= d.ingredient.name %> (<%= d.description %>) <%= link_to 'Delete', dose_path(d), method: :delete %></li>
<% end %>
<% if policy(Dose).create? %>
<p style="margin-top: 15px"><%= link_to 'Add ingredients', new_cocktail_dose_path(@cocktail) %></p>
<% end %>
</ul>

<p><%= link_to 'Edit this cocktail', edit_cocktail_path %></p>
<p><%= link_to 'Delete this cocktail', cocktail_path, method: :delete %></p>
<p><%= link_to 'Go back to cocktails', cocktails_path %></p>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
<div class="form-group">
  <%= f.association :ingredient, collection: Ingredient.all %>
</div>
<div class="form-group">
  <%= f.input :description, label: 'Enter quantity' %>
</div>
<%= f.submit 'Add ingredient' %>
<% end %>

app/views/doses/new.html.erb
<h1>Add ingredients:</h1>
<div class="form">
<%= render 'form', cocktail: @cocktail, dose: @dose %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

    <%= javascript_include_tag 'application' %>
  <body>
    <%= render 'shared/navbar' unless defined? @hide %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/splash.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path "https://res.cloudinary.com/dftybtoej/image/upload/v1541479566/cocktail.jpg" %>');">
  <div class="banner-content">
    <h1>Cocktail Fairy</h1>
    <p><span id="banner-typed-text"></span></p>
    <%= link_to 'Enter', cocktails_path, { class: 'btn btn-primary btn-lg', style: 'width: 250px; border-radius: 10px' } %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to cocktails_path, class: 'navbar-wagon-brand' do  %>
  <%= image_tag "https://res.cloudinary.com/dftybtoej/image/upload/v1541478136/cocktail_logo.jpg" %>
  <% end %>

  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <%= link_to 'Add cocktail', new_cocktail_path, { class: 'navbar-wagon-item navbar-wagon-link' } %>
    <%= link_to 'View cocktails', cocktails_path, { class: 'navbar-wagon-item navbar-wagon-link' } %>
    <%= link_to destroy_user_session_path, method: :delete do %>
    <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
    <% end %>

    <% else %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <%= link_to 'Add cocktail', new_cocktail_path, { class: 'navbar-wagon-item navbar-wagon-link' } %>
        <%= link_to 'View cocktails', cocktails_path, { class: 'navbar-wagon-item navbar-wagon-link' } %>
      </ul>
    </div>
  </div>
</div>